export const DATE_FORMATS = Object.freeze({
  dateDisplay: 'yyyy/MM/dd',
  dateDisplayFull: 'yyyy/MM/dd HH:mm:ss',
  dateOnlyFull: 'yyyy-MM-dd HH:mm:ss',
  dateOnly: 'yyyy-MM-dd',
  dateWithSpace: 'dd MMMM yyyy',
  timeOnly: 'HH:mm',
  timeAmPm: 'hh:mma',
  timeDisplay: 'hh:mm a',
  fullTime: 'HH:mm:ss',
  hour: 'hh',
  minute: 'mm',
  amPm: 'a',
  dayName: 'E',
  dayNumber: 'd',
  dayMonth: 'd MMMM',
  fullDateWithName: 'EEEE d MMMM yyyy',
  fullDate: 'd MMMM yyyy',
  monthAndYear: 'MMMM yyyy',
  japaneseMonthAndYear: 'yyyy年MMMM',
  monthYear: 'MM-yyyy',
  minuteSecond: 'mm : ss',
  year: 'yyyy',
  month: 'MMMM',
  days: 'd',
  japaneseDay: 'd日',
  dateDisplayAmPM: 'yyyy/MM/dd hh:mm a',
  dateRaw: "yyyy-MM-dd HH:mm:ss.SSSSSS XXXX 'UTC'",
  dateTZ: "yyyy-MM-dd'T00:00:00Z'",
  dateMonth: 'MM/dd',
  japaneseFullDate: 'yyyy年MM月dd日',
  japaneseDayMonth: 'MM月dd日',
  japaneseYear: 'yyyy年',
  monthShort: 'MMM',
  monthNumber: 'MM',
});
