export const REGEX_PATTERNS = Object.freeze({
  EMAIL: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  PHONE: /^[0-9]+$/,
  NUMBER: /^[0-9]+$/,
  NUMBER_GLOBAL: /[0-9]/g,
  NONDIGIT: /\D/g,
  COORDINATES: /^(?:-?\d+(?:\.\d+)?),\s*(?:-?\d+(?:\.\d+)?)$/,
  ZEROONFRONT: /^0+/,
  HTML_TAG: /(<([^>]+)>)/gi,
  ANYTHING: /./g,
  HTML_CONTAIN_COLOR: /<[^>]*color: ?[^>]*>/gi,
  ALPHABET: /^[a-zA-Z ]+$/,
  ALPHANUMERIC: /^[a-zA-Z0-9 ]+$/,
  WORD: /\w\S*/g,
  SPACE: /\s/g,
  URL: /^((http|https):\/\/.)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)$/,
  DAY: /d{1,2}/,
  ADDRESS: /^[a-zA-Z0-9\s,'-.]*$/,
  NAME: /^[a-zA-Z\s,'-.]*$/,
  OTHER_ALPHANUMERIC: /[^a-zA-Z0-9 ]/,
  OTHER_ALPHABET: /[^a-zA-Z ]/,
  NUMBER_DOT: /[^0-9\.]/g,
  MERGE_FIELDS: /({{\.[A-z]+}})/g,
  DOT: /\.+$/,
});
